### ISSUE TITLE
Add `auto` config to `nim.buildCommand` for multi-target projects

### ISSUE THREAD

**Issue by nc-x** [saem/vscode-nim#20]
If we have `A.nim` that compiles to `c` and `B.nim` that compiles to `js`, then `nim.buildCommand` is problematic because it will run `nim check` (and nimsuggest?) with the wrong backend for one of the files.

The better way is to have a file `B.nim.cfg` with `backend=js`, so that `nim` runs with the correct backend.

However, because command line args take priority over `.cfg`, therefore, due to `nim.buildCommand` it is currently not working.

So, I suggest adding a `auto` option for `nim.buildCommand` (that does not pass `--backend:xxx` argument to `nim`)  and making it the default.

**Comment by saem** [comment]
The whole project, project mapping, and backend bits are regrettable. I've been considering a more sweeping change but it's not as clear in my head as I would like otherwise I'd be much closer to done.

I'm a little reluctant of introducing auto, but this extension is young and I could live with changing the settings schema in a breaking fashion in the future.

I'm thinking perhaps extending project and project mapping to accept an object in the value side wherein one can specify a backend and if they don't then the existing in is used as a default. How's that sound as something near term?

It's still a bit stop gap but closer to where I would like things to go, which is in the direction of declaring an accumulating set of compilation settings describing the relevant artifacts one wants to build. If we have that description then we know what someone wants to analyse, debug, check, search, and ask the rest, asking with the relevant settings. Then if it's not in there it's either one of or a 3rd party import, in which case best effort is fine. Seem like the right direction long term?
