### ISSUE TITLE
How to get code completion working?

### ISSUE THREAD

**Issue by geekrelief** [saem/vscode-nim#23]
I'm using godot-nim which has a bit of a weird structure.  Most of the code is inside of a macro that gets rewritten. 

Here's a small example:
https://github.com/geekrelief/gdnim/blob/master/components/bullet.nim

The code gets built with paths to the imported modules passed in via compiler flags, and there's quite a bit of macro "magic" happening.

I noticed nimsuggest doesn't produce any useful results, and just about everyone is talking about using TabNine.  Any suggestions on improving code completion?

**Comment by saem** [comment]
There is a macro related fix which significantly impacts nimsuggest's behavior for the better with the light testing I've done.

It's not been merged as the [PR](https://github.com/nim-lang/Nim/pull/16840) doesn't have all the tests passing yet. Once that's done updating Nim to the latest development build anytime after that should give a better indication as to what else might be required in your situation. 

In the meantime I would ensure that you have set  [nim.project](https://github.com/geekrelief/gdnim/blob/master/.vscode/settings.json#L10) setting to ensure the correct entry point for your game. Generally the one or two files one usually passes to the compiler should be specified here.

**Comment by geekrelief** [comment]
Nice!  That PR sounds promising.  Hopefully, that and another bug that's blocking me from updating nim comes soon.  

My project consists of many independent components, each getting compiled to their own dll.  Would I have to list each of them in the nim.project setting or can I specify a directory or wildcard '*'?  Do I also include module dependencies there too? For example `--path:deps/godotapi` is passed to the compiler to build the component.

Thanks for your help!

**Comment by saem** [comment]
General rule, each unique Nim project file (Nim file you pass to the compiler) that gets some artifact out of should be listed there.

If I was working with your code blindly, I would simply list the one project file that gets compiled and either directly or transitively includes all other files regardless of whether that's statically or dynamically linked. Then if there are suggest gaps add a project file for those lather, rinse, repeat.

There is another setting that I understand far less and came along with the port, which is `nim.projectmappings`. that does the wildcard thing. I believe it's project file to pattern map.

Module dependencies, unless those are entirely independently compiled aren't a problem as they get imported so nimsuggest which is effectively just the compiler frontend will do the legwork traverse the imports. So no you shouldn't have to.

If the dll compilation is simply for hot code reloading, but otherwise one can effectively think of them as plain Nim modules that get imported, then don't bother specifying those independently as nimsuggest shouldn't care. This is something that requires a bit of experimentation, so start lazy. ;) The key here is if you can statically build the whole thing and outside of the hot reload everything works and there are no significant sections of code that are behind conditional compilation which checks for whether something is the main module, or dll, or whatever, it does not need to be listed.

**Comment by geekrelief** [comment]
Forgive me for being dense.  I get that I could include my nim files into `nim.project`. How does nimsuggest pull in external dependencies?  Don't I have to supply a path somewhere? In my code I `import godotapi / node`, but that exists in `deps/godotapi/node.nim`.  Listing all the files I would need from godotapi without a wildcard would be a nuisance unless `nim.projectmappings` is what I'm looking for.  Though I don't know where that's documented other than the source.

FYI, the dlls essentially are static.

**Comment by saem** [comment]
Nimsuggest is the compiler less the c, JS, etc code gen. If you can do `nim c foo.nim` and it builds then nimsuggest will work, too.

It'll look up all the same stuff, use all the same configs, etc... that's how you can keep project files minimal.

**Comment by geekrelief** [comment]
Thanks for clarifying! It wasn't apparent to me that nimsuggest could accept nim flags based on the [docs](https://nim-lang.org/docs/nimsuggest.html).  I tried running `nimsuggest --stdin --debug --path:deps --path:deps/godot components/sprite_comp.nim` and was able to pull up a suggestion on this line of code
```nim
    self.add_child(self.timer
```
```
sug components/sprite_comp.nim:24:9 
.sug    skProc  node.addChildBelowNode  proc (self: Node, node: Node, childNode: Node, legibleUniqueName: bool){.gcsafe, locks: 0.}                  C:\godot\gdnim_hb_arpg\deps\godotapi\node.nim    519     5       ""      0      Prefix
```

But it doesn't return `addChild` as an option.  Anyway, this is progress.  I have a custom build system that passes the path flag to nim for compilation.  I avoided using config files for the most part because as a beginner using godot-nim I was confused by the nake, config files, nimscript all be used to configure things.  I guess I'll have to create a .cfg file instead.

Thanks for the help!  Going to experiment with this a bit more to see if I can get better autocompletion before closing the issue.

**Comment by geekrelief** [comment]
I created a nim.cfg file with some path flags, and I'm getting autocomplete! Thanks again!

**Comment by saem** [comment]
@geekrelief could I ask you to add a docs PR, either to the readme, the help text for the project setting in package.json, or whatever makes sense for a few of the things you learned here?

Doesn't have to be much, I would appreciate capturing some lessons so it eases some future questions and workload. Thanks.

**Comment by geekrelief** [comment]
I'd be glad to create a PR for the README.  Though the easiest would be to reopen this comment and leave it as an open issue.  It was the second place I checked, after doing a keyword search for "completion" in the README.  

The key insight for me was when you mentioned nimsuggest is just a frontend for nim and thus uses config files.  That's why I repeatedly asked about how nimsuggest would get access to extra dependencies defined by `--path`.  This connection is basically just implied, so in a sense undocumented, unless you're familiar with nimsuggest before using the vscode extension.  So reason why I wasn't getting any autocomplete suggestions is because nimsuggest wasn't able to "compile" my project.  

Would it make sense to cover nimsuggest's details in the README?

**Comment by saem** [comment]
@geekrelief yeah, I think a comment encouraging the project and config file because nimsuggest and compiler relationship would be great, thanks.

I'll reopen this issue and a PR can close it.

**Comment by geekrelief** [comment]
I sent PR.  Not sure if you noticed.

**Comment by saem** [comment]
Thanks.
