### ISSUE TITLE
Build task is run on each keystroke

### ISSUE THREAD

**Issue by dsrw** [saem/vscode-nim#3]
My build task is being run on each keystroke rather than on file save. I'm happy to debug this myself (I expect there's something weird about my environment). Where would you suggest I start looking?

**Comment by saem** [comment]
I had a quick look at this, found a few small bugs but not something that would kick off a build each time.

Few obvious issues:
* is build on save and that's overly aggresive
* the nimsuggest/check processes are being a call too much because of a bug in the suggest provider

If you pull down the plugin you can setup a pretty quick dev environment following the vs code guide. Otherwise, I'll see if I have time check it out later, working on fixing other things right now.

**Comment by saem** [comment]
I believe this is fixed, give it a shot.

**Comment by dsrw** [comment]
Yep. Thanks!
