### ISSUE TITLE
javascript backend not working

### ISSUE THREAD

**Issue by dullbananas** [saem/vscode-nim#38]
in the extension settings i set the compile command to "js" but i still get this error when trying to import std/jsffi:

Module jsFFI is designed to be used with the JavaScript backend.

**Comment by saem** [comment]
The extension used to force passing the backend on the command line to nim check, suggest, etc... but that forces an override of anything in a cfg, which leads to bigger problems.

Long story short, use the cfg mechanism in order to get your preferred backend.

(this should probably be in a FAQ or something in the README? 🤔)
