### ISSUE TITLE
autocompletion requires the module to be imported

### ISSUE THREAD

**Issue by jcornaz** [saem/vscode-nim#95]
Hi, 

The autocompletion does not suggest what is not already imported.

I would expect to see autocompletion even for stuff that is not yet imported, and if I accept the suggestion, it should add the import.

**Comment by saem** [comment]
That's not how nimsuggest (the compiler) works. The list of symbols that aren't in scope aren't suggested. That precludes adding them in and consequently adding in the import.

There are other complications as one could be inside a top level when block and it's unclear where the import should be auto-added.

I did want to add this a while back but it was edge case after edge case. We have a symbol index that we might be able to leverage but there could well be other issues such as dealing with existing import except or import from etc.

If you want to take a stab at implementing it you can reopen this issue, otherwise I'm afraid it's not feasible.

**Comment by jcornaz** [comment]
Ok. That's a shame. But thank you for the quick answer.
